// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMnEF157eakYQCUghgLDvr0IGKEXhhWx0',
    appId: '1:60712410528:web:8ffbc9e0df19f8793d18c5',
    messagingSenderId: '60712410528',
    projectId: 'first-d1d3e',
    authDomain: 'first-d1d3e.firebaseapp.com',
    storageBucket: 'first-d1d3e.firebasestorage.app',
    measurementId: 'G-B77YL7CE8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCprrix5N0tFmTy-c9a9-raFWrGKMgMWd4',
    appId: '1:60712410528:android:0d9f8fb1fb9564ff3d18c5',
    messagingSenderId: '60712410528',
    projectId: 'first-d1d3e',
    storageBucket: 'first-d1d3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK14JY8du4LybiBQcWSGdrF09a48rjqsY',
    appId: '1:60712410528:ios:200555f3c48ec2a23d18c5',
    messagingSenderId: '60712410528',
    projectId: 'first-d1d3e',
    storageBucket: 'first-d1d3e.firebasestorage.app',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK14JY8du4LybiBQcWSGdrF09a48rjqsY',
    appId: '1:60712410528:ios:200555f3c48ec2a23d18c5',
    messagingSenderId: '60712410528',
    projectId: 'first-d1d3e',
    storageBucket: 'first-d1d3e.firebasestorage.app',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMnEF157eakYQCUghgLDvr0IGKEXhhWx0',
    appId: '1:60712410528:web:62e5b08faece93653d18c5',
    messagingSenderId: '60712410528',
    projectId: 'first-d1d3e',
    authDomain: 'first-d1d3e.firebaseapp.com',
    storageBucket: 'first-d1d3e.firebasestorage.app',
    measurementId: 'G-4428T9DENF',
  );
}
